### ISSUE TITLE
RTTVAR has grown to over 2.3 seconds

### ISSUE THREAD

**Issue by MROSSFTEK** [LoH-lu/netbox-nmap-scan#6]
im running your scripts, when i run the DNS script i get this error.
i think its an issue with nmap, but can you offer any solutions?

**Comment by LoH-lu** [comment]
Hi @MROSSFTEK, can you send the error you get ?

Thanks

**Comment by LoH-lu** [comment]
I've just pushed an update to nmap_scan that should hopefully resolve your issue.
You can open a new issue if needed
